spring.application.name=UpravljanjeBudetom
spring.datasource.url=jdbc:mysql://localhost:3307/upravljanje_budetom?&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tvoj_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9090

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=moj-tajni-kljuc-123456789101112131415
jwt.expiration=86400000

jwt.refresh-token.secret=3nX8pL1qW6tY9rE2oI5uA7sD4fG0hJ3kZ6xC8vB1nM4qW7eR0tY5uI2oP9aS3dF6
jwt.refresh-token.expiration=604800000

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always